import fs from 'node:fs'
import * as esbuild from 'esbuild'
import * as ctx from './context.mjs'

/*
 * https://esbuild.github.io/analyze/
 *  - metafiles.json files are generated by this script to analyze the build
 */
esbuild.build(ctx.nodeCjs).then((result) => {
  fs.writeFileSync('dist/node-cjs-metafile.json', JSON.stringify(result.metafile))
})
esbuild.build(ctx.nodeEsm).then((result) => {
  fs.writeFileSync('dist/node-esm-metafile.json', JSON.stringify(result.metafile))
})
esbuild.build(ctx.browserCjs).then((result) => {
  fs.writeFileSync('dist/browser-cjs-metafile.json', JSON.stringify(result.metafile))
})
esbuild.build(ctx.browserEsm).then((result) => {
  fs.writeFileSync('dist/browser-esm-metafile.json', JSON.stringify(result.metafile))
})
