name: Build example
on:
  push:
    branches: ['release/hip-820', 'feature/pages']
  pull_request:
    branches: ['release/hip-820']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: npm install
      - name: Build lib and example
        run: |
          npm run build
          npm run build:example
